More phpstan fixes
liuch/dmarc-srg pull request #78
Opened 2023-06-20 12:42 UTC by williamdes

I fixed one actual unreachable code in 59d638d547a72889ad7ff6ae72bda1446ef10175

The other changes are purely phpdocs

That said I am not sure about the phpdoc ones for DatabaseConnector since the comment was `@param Connector $connector DatabaseConnector`. Let me know

2023-06-20 12:45 UTC, williamdes commented
That all for this PR: `Found 423 errors` left 😄 
Mostly phpdocs

2023-06-21 01:41 UTC, liuch requested changes

2023-06-21 01:41 UTC, liuch commented on classes/Database/Mariadb/DomainMapper.php
> +     * @param \Liuch\DmarcSrg\Database\DatabaseConnector $connector
```suggestion
     * @param \Liuch\DmarcSrg\Database\DatabaseConnector $connector DatabaseConnector instance of the current database
```

2023-06-21 01:41 UTC, liuch commented on classes/Database/Mariadb/ReportLogMapper.php
> +     * @param \Liuch\DmarcSrg\Database\DatabaseConnector $connector
```suggestion
     * @param \Liuch\DmarcSrg\Database\DatabaseConnector $connector DatabaseConnector instance of the current database
```

2023-06-21 01:41 UTC, liuch commented on classes/Database/Mariadb/ReportMapper.php
> +     * @param \Liuch\DmarcSrg\Database\DatabaseConnector $connector
```suggestion
     * @param \Liuch\DmarcSrg\Database\DatabaseConnector $connector DatabaseConnector instance of the current database
```

2023-06-21 01:41 UTC, liuch commented on classes/Database/Mariadb/SettingMapper.php
> +     * @param \Liuch\DmarcSrg\Database\DatabaseConnector $connector
```suggestion
     * @param \Liuch\DmarcSrg\Database\DatabaseConnector $connector DatabaseConnector instance of the current database
```

2023-06-21 01:41 UTC, liuch commented on classes/Database/Mariadb/StatisticsMapper.php
> +     * @param \Liuch\DmarcSrg\Database\DatabaseConnector $connector
```suggestion
     * @param \Liuch\DmarcSrg\Database\DatabaseConnector $connector DatabaseConnector instance of the current database
```

2023-06-21 01:41 UTC, liuch commented on classes/Database/Mariadb/UpgraderMapper.php
> +     * @param Connector $connector
```suggestion
     * @param Connector $connector DatabaseConnector instance of the current database
```

2023-06-26 00:16 UTC, merged

2023-06-26 11:14 UTC, williamdes commented
Thank you @liuch for making the changes
I was missing time to get back to this this week

2023-06-26 14:31 UTC, liuch commented
It's okay.